version: '3.7'
services:
    postgres:
        image: postgres
        environment:
            - POSTGRES_USER=
            - POSTGRES_PASSWORD=
            - POSTGRES_DB=
            - POSTGRES_HOST=postgres
            - POSTGRES_PORT=5432
        logging:
            options:
                max-size: 10m
                max-file: "3"
        ports:
            - "5432"

    webserver:
        image: sparkify
        restart: always
        depends_on:
            - postgres
        environment:
            - LOAD_EX=n
            - EXECUTOR=Local
        logging:
            options:
                max-size: 10m
                max-file: "3"
        volumes:
            - ./dags:/app/airflow/dags
            - ./plugins:/app/airflow/plugins
            - ./requirements.txt:/app/requirements.txt
            - ./glue_etl_scripts:/app/glue_etl_scripts
        ports:
            - "8080:8080"
        
        command: webserver
        healthcheck:
            test: ["CMD-SHELL", "[ -f /app/airflow/airflow-webserver.pid ]"]
            interval: 30s
            timeout: 30s
            retries: 3

